import type {
  AuditEvent,
  Conversation,
  KnowledgeSignal,
  Lesson,
  ParentSummary,
  PlanDraft,
  Quiz,
  SafetyCase,
  Student,
  Task,
} from "./types"

const studentIds = [
  "student-lin-xiaoyu",
  "student-chen-hao",
  "student-wang-yutong",
  "student-li-mingze",
  "student-zhao-xinyi",
  "student-zhou-zimo",
  "student-sun-yinuo",
  "student-wu-jiaqi",
  "student-xu-ziyan",
  "student-guo-haoran",
  "student-he-yuchen",
  "student-tang-ruoxi",
] as const

export const lessonFixtures: Lesson[] = [
  {
    id: "lesson-fractions",
    title: "分数的基本性质",
    subject: "数学",
    grade: "五年级",
    className: "五年级（2）班",
    date: "2026-07-21",
    durationMinutes: 40,
    status: "draft-ready",
    syncStatus: "synced",
    studentVisibility: "hidden",
    recap: "分子和分母同时乘或除以相同的数，分数的大小不变。",
    recapTags: ["约分", "分数基本性质", "自检问题"],
    transcript: [
      {
        id: "transcript-fractions-01",
        speaker: "李老师",
        startSeconds: 85,
        endSeconds: 112,
        body: "分子和分母要同时乘同一个不为零的数，分数值才不会改变。",
        evidenceFor: ["suggestion-fractions-01"],
      },
      {
        id: "transcript-fractions-02",
        speaker: "学生",
        startSeconds: 952,
        endSeconds: 978,
        body: "如果只把分子乘二，分数是不是也一样？",
        evidenceFor: ["suggestion-fractions-01"],
      },
    ],
    suggestions: [
      {
        id: "suggestion-fractions-01",
        title: "补充不为零的条件",
        body: "复习卡可明确“相同且不为零的数”，避免学生忽略适用条件。",
        confidence: "high",
        status: "pending",
        evidenceIds: ["transcript-fractions-01", "transcript-fractions-02"],
      },
    ],
    progress: {
      chapter: "第四单元 · 分数的意义和性质",
      completedPercent: 72,
      nextStep: "约分与通分",
    },
  },
  {
    id: "lesson-units",
    title: "单位换算中的乘除步骤",
    subject: "数学",
    grade: "五年级",
    className: "五年级（2）班",
    date: "2026-07-24",
    durationMinutes: 42,
    status: "published",
    syncStatus: "synced",
    studentVisibility: "visible",
    recap: "先判断单位变大还是变小，再选择乘或除以相应的进率。",
    recapTags: ["单位换算", "进率", "计算步骤"],
    transcript: [
      {
        id: "transcript-units-01",
        speaker: "李老师",
        startSeconds: 420,
        endSeconds: 451,
        body: "大单位换成小单位，数值通常变大，要乘进率。",
        evidenceFor: ["suggestion-units-01"],
      },
    ],
    suggestions: [
      {
        id: "suggestion-units-01",
        title: "增加单位阶梯图",
        body: "部分学生在确定乘除方向时停顿，可增加视觉化阶梯。",
        confidence: "medium",
        status: "accepted",
        evidenceIds: ["transcript-units-01"],
      },
    ],
    progress: {
      chapter: "第三单元 · 小数乘除法",
      completedPercent: 88,
      nextStep: "单位换算综合应用",
    },
  },
  {
    id: "lesson-decimals",
    title: "小数乘法估算",
    subject: "数学",
    grade: "五年级",
    className: "五年级（2）班",
    date: "2026-07-25",
    durationMinutes: 40,
    status: "scheduled",
    syncStatus: "local",
    studentVisibility: "hidden",
    recap: "",
    recapTags: ["估算", "小数乘法"],
    transcript: [],
    suggestions: [],
    progress: {
      chapter: "第三单元 · 小数乘除法",
      completedPercent: 90,
      nextStep: "小数除法",
    },
  },
]

const studentNames = [
  ["student-lin-xiaoyu", "林晓雨", "林妈妈", "母亲"],
  ["student-chen-hao", "陈浩", "陈爸爸", "父亲"],
  ["student-wang-yutong", "王雨桐", "王妈妈", "母亲"],
  ["student-li-mingze", "李明泽", "李爸爸", "父亲"],
  ["student-zhao-xinyi", "赵心怡", "赵妈妈", "母亲"],
  ["student-zhou-zimo", "周子墨", "周妈妈", "母亲"],
  ["student-sun-yinuo", "孙一诺", "孙爸爸", "父亲"],
  ["student-wu-jiaqi", "吴佳琪", "吴妈妈", "母亲"],
  ["student-xu-ziyan", "徐子言", "徐爸爸", "父亲"],
  ["student-guo-haoran", "郭浩然", "郭妈妈", "母亲"],
  ["student-he-yuchen", "何雨辰", "何爸爸", "父亲"],
  ["student-tang-ruoxi", "唐若曦", "唐妈妈", "母亲"],
] as const

export const studentFixtures: Student[] = studentNames.map(
  ([id, name, guardianName, guardianRelation], index) => ({
    id,
    name,
    avatarText: name.slice(-1),
    className: "五年级（2）班",
    grade: "五年级",
    guardianName,
    guardianRelation,
    voluntaryQuestions: id === "student-lin-xiaoyu" ? 4 : (index % 4) + 1,
    practiceCount: id === "student-lin-xiaoyu" ? 7 : 4 + (index % 5),
    taskCompletionRate: 72 + (index % 6) * 5,
    currentFocus:
      index < 4
        ? ["单位换算", "计算步骤"]
        : index < 8
          ? ["分数基本性质"]
          : ["小数乘法"],
    facts: [
      `本周主动提问 ${id === "student-lin-xiaoyu" ? 4 : (index % 4) + 1} 次`,
      `完成练习 ${id === "student-lin-xiaoyu" ? 7 : 4 + (index % 5)} 次`,
    ],
    aiInferences: [
      index < 4
        ? "可能需要更多单位换算步骤提示，需结合后续练习人工确认。"
        : "近期练习节奏稳定，仍需结合课堂表现人工确认。",
    ],
    teacherNotes: [],
    mistakes:
      id === "student-lin-xiaoyu"
        ? [
            {
              id: "mistake-fraction-seed",
              subject: "数学",
              knowledgePoint: "分数的基本性质",
              prompt: "分子乘 2 时，分母应该怎样变化？",
              cause: "只关注分子变化",
              explanation: "为了保持分数值不变，分母也要乘 2。",
              mastery: "learning",
              source: "lesson",
              createdAt: "2026-07-22T16:20:00+08:00",
            },
          ]
        : [],
    timeline: [
      {
        id: `timeline-${id}-01`,
        type: "review",
        title: "查看课堂复习卡",
        detail: index < 4 ? "完成分数基本性质自检" : "完成本周课堂回顾",
        occurredAt: `2026-07-${22 + (index % 3)}T19:20:00+08:00`,
        fact: true,
      },
      {
        id: `timeline-${id}-02`,
        type: "task",
        title: "完成教师任务",
        detail: "提交后等待教师查看",
        occurredAt: `2026-07-${23 + (index % 2)}T20:10:00+08:00`,
        fact: true,
      },
    ],
  }),
)

export const knowledgeSignalFixtures: KnowledgeSignal[] = [
  {
    id: "signal-unit-calculation",
    subject: "数学",
    knowledgePoint: "单位换算",
    step: "判断乘除方向",
    severity: "priority",
    affectedStudentIds: studentIds.slice(0, 12) as unknown as string[],
    affectedCount: 12,
    trend: [4, 6, 8, 10, 12],
    evidence: ["随堂练习第 3 题停顿时间增加", "课堂中 5 次询问乘还是除"],
    observedAt: "2026-07-25T08:40:00+08:00",
  },
  {
    id: "signal-fraction-condition",
    subject: "数学",
    knowledgePoint: "分数基本性质",
    step: "理解同时变化条件",
    severity: "attention",
    affectedStudentIds: studentIds.slice(0, 7) as unknown as string[],
    affectedCount: 7,
    trend: [3, 5, 6, 7, 7],
    evidence: ["7 名学生忽略“不为零”条件"],
    observedAt: "2026-07-24T15:30:00+08:00",
  },
  {
    id: "signal-decimal-estimation",
    subject: "数学",
    knowledgePoint: "小数乘法估算",
    step: "选择合理近似数",
    severity: "watch",
    affectedStudentIds: studentIds.slice(8, 12) as unknown as string[],
    affectedCount: 4,
    trend: [2, 3, 3, 4, 4],
    evidence: ["预习自检中 4 名学生选择不合理近似值"],
    observedAt: "2026-07-25T07:50:00+08:00",
  },
]

export const planFixtures: PlanDraft[] = [
  {
    id: "plan-units-remedial",
    title: "单位换算步骤补讲",
    subject: "数学",
    grade: "五年级",
    chapter: "单位换算",
    objective: "先判断单位变化方向，再确定乘除进率",
    context: "校园菜园长度测量",
    evidence: ["12 名学生在“单位换算 × 计算”步骤停下来"],
    outline: ["回顾单位关系", "单位阶梯示范", "同伴解释", "出口练习"],
    examples: ["2.5 米换算成厘米", "4800 克换算成千克"],
    misconceptions: ["只改单位名称不改数值", "乘除方向颠倒"],
    suggestions: ["用箭头标示数值变化", "要求学生先口述判断"],
    extension: "让学生设计一道生活中的单位换算题",
    status: "ready",
    createdAt: "2026-07-25T08:55:00+08:00",
  },
]

export const quizFixtures: Quiz[] = [
  {
    id: "quiz-fractions-check",
    title: "分数基本性质自检",
    subject: "数学",
    lessonId: "lesson-fractions",
    status: "published",
    createdAt: "2026-07-22T09:30:00+08:00",
    questions: [
      {
        id: "question-fractions-01",
        prompt: "3/5 的分子和分母同时乘 2，得到哪个分数？",
        type: "single-choice",
        options: ["6/5", "6/10", "3/10"],
        answer: "6/10",
        explanation: "分子和分母同时乘 2，分数值不变。",
        score: 5,
      },
      {
        id: "question-fractions-02",
        prompt: "分数基本性质中的相同数可以是 0 吗？",
        type: "single-choice",
        options: ["可以", "不可以"],
        answer: "不可以",
        explanation: "分母不能为 0，因此相同数也必须不为 0。",
        score: 5,
      },
      {
        id: "question-fractions-03",
        prompt: "请用自己的话解释为什么分数值不变。",
        type: "short-answer",
        options: [],
        answer: "相当于分子和分母同时乘同一个 1。",
        explanation: "同步扩大或缩小相同倍数，不改变整体所表示的比例。",
        score: 10,
      },
    ],
  },
]

const baseCompletions = studentIds.map((studentId, index) => ({
  studentId,
  status: index < 8 ? ("reviewed" as const) : index < 10 ? ("submitted" as const) : ("in-progress" as const),
  submittedAt: index < 10 ? `2026-07-24T${18 + (index % 3)}:20:00+08:00` : undefined,
  score: index < 8 ? 80 + (index % 4) * 5 : undefined,
}))

export const taskFixtures: Task[] = [
  {
    id: "task-draft-01",
    title: "小数乘法预习",
    type: "reading",
    content: "阅读知识卡并写下一个问题",
    audience: { kind: "class", label: "五年级（2）班", studentIds: [] },
    dueAt: "2026-07-28T20:00:00+08:00",
    reminder: "截止前 1 天",
    status: "draft",
    completions: [],
    createdAt: "2026-07-25T08:10:00+08:00",
  },
  {
    id: "task-active-01",
    title: "单位换算巩固练习",
    type: "practice",
    content: "完成 5 道单位换算题并说明乘除理由",
    audience: { kind: "class", label: "五年级（2）班", studentIds: [] },
    dueAt: "2026-07-26T20:00:00+08:00",
    reminder: "截止前 2 小时",
    status: "active",
    completions: baseCompletions,
    createdAt: "2026-07-24T16:00:00+08:00",
  },
  {
    id: "task-review-01",
    title: "分数基本性质自检",
    type: "quiz",
    content: "完成三道自检题",
    audience: { kind: "class", label: "五年级（2）班", studentIds: [] },
    dueAt: "2026-07-25T20:00:00+08:00",
    reminder: "截止前 2 小时",
    status: "review",
    completions: baseCompletions.map((item, index) => ({
      ...item,
      status: index < 10 ? ("submitted" as const) : ("in-progress" as const),
      score: undefined,
    })),
    createdAt: "2026-07-23T15:40:00+08:00",
  },
  {
    id: "task-completed-01",
    title: "约分与通分复习",
    type: "review",
    content: "查看复习卡并完成口头复述",
    audience: { kind: "class", label: "五年级（2）班", studentIds: [] },
    dueAt: "2026-07-23T20:00:00+08:00",
    reminder: "不提醒",
    status: "completed",
    completions: studentIds.map((studentId) => ({
      studentId,
      status: "reviewed" as const,
      submittedAt: "2026-07-23T19:30:00+08:00",
    })),
    createdAt: "2026-07-21T17:10:00+08:00",
  },
]

export const conversationFixtures: Conversation[] = [
  {
    id: "conversation-student-xiaoyu",
    kind: "student",
    title: "林晓雨",
    participantIds: ["teacher-li", "student-lin-xiaoyu"],
    participantNames: ["李老师", "林晓雨"],
    boundStudentId: "student-lin-xiaoyu",
    unreadCount: 1,
    messages: [
      {
        id: "message-student-01",
        senderId: "student-lin-xiaoyu",
        senderName: "林晓雨",
        senderRole: "student",
        body: "老师，我还是不太明白为什么要同时乘。",
        sentAt: "2026-07-25T08:12:00+08:00",
      },
    ],
  },
  {
    id: "conversation-parent-li",
    kind: "parent",
    title: "林晓雨家长",
    participantIds: ["teacher-li", "parent-lin-xiaoyu"],
    participantNames: ["李老师", "林妈妈"],
    boundStudentId: "student-lin-xiaoyu",
    unreadCount: 2,
    messages: [
      {
        id: "message-parent-01",
        senderId: "parent-lin-xiaoyu",
        senderName: "林妈妈",
        senderRole: "parent",
        body: "老师您好，今晚适合陪孩子复习哪一部分？",
        sentAt: "2026-07-25T07:50:00+08:00",
      },
      {
        id: "message-parent-02",
        senderId: "teacher-li",
        senderName: "李老师",
        senderRole: "teacher",
        body: "可以一起看分数基本性质复习卡，让孩子用自己的话讲一遍。",
        sentAt: "2026-07-25T08:02:00+08:00",
      },
    ],
  },
  {
    id: "conversation-group-class-2",
    kind: "group",
    title: "五年级（2）班学习群",
    participantIds: ["teacher-li", ...studentIds],
    participantNames: ["李老师", "五年级（2）班学生"],
    unreadCount: 0,
    messages: [
      {
        id: "message-group-01",
        senderId: "teacher-li",
        senderName: "李老师",
        senderRole: "teacher",
        body: "今晚请完成分数基本性质自检，遇到困难可以留言。",
        sentAt: "2026-07-24T17:20:00+08:00",
      },
    ],
  },
]

export const parentSummaryFixture: ParentSummary = {
  id: "parent-summary-week-2026-30",
  studentId: "student-lin-xiaoyu",
  studentName: "林晓雨",
  className: "五年级（2）班",
  weekLabel: "7 月 20 日—7 月 26 日",
  topics: ["分数的基本性质", "约分", "单位换算"],
  voluntaryQuestions: 4,
  practiceCount: 7,
  encouragement: "孩子愿意把不明白的地方说出来，这份主动很珍贵。",
  teacherMessage: "本周可以陪孩子用生活里的比例例子复述分数基本性质，不需要额外刷题。",
  audioLetter: {
    title: "李老师的本周语音信",
    durationSeconds: 48,
    simulated: true,
  },
}

export const safetyCaseFixtures: SafetyCase[] = [
  {
    id: "safety-case-01",
    title: "需要人工核实的学生表达",
    signal: "学生在私信中表达“不敢回家”",
    source: "student-message",
    status: "new",
    priority: "urgent",
    studentAlias: "五年级学生 A",
    className: "五年级（2）班",
    limitedContext: "仅展示触发人工核实所需的最少上下文，不作诊断或结论。",
    guidance: ["由受过培训的负责人核实", "必要时联系校内可信任成年人", "紧急危险应联系当地紧急服务"],
    notes: [],
    createdAt: "2026-07-25T08:15:00+08:00",
    updatedAt: "2026-07-25T08:15:00+08:00",
  },
  {
    id: "safety-case-02",
    title: "连续缺席后的关怀核实",
    signal: "教师观察到学生连续两次缺席并明显回避交流",
    source: "teacher-observation",
    status: "reviewing",
    priority: "high",
    studentAlias: "五年级学生 B",
    className: "五年级（1）班",
    limitedContext: "展示教师记录的事实，不包含未经核实的推断。",
    guidance: ["与班主任共同核实", "记录事实与后续联系"],
    assignee: "王老师 · 德育负责人",
    notes: [
      {
        id: "safety-note-02-01",
        author: "王老师",
        body: "已与班主任确认缺席记录，等待监护人回电。",
        createdAt: "2026-07-24T15:30:00+08:00",
      },
    ],
    createdAt: "2026-07-24T10:20:00+08:00",
    updatedAt: "2026-07-24T15:30:00+08:00",
  },
  {
    id: "safety-case-03",
    title: "重复求助关键词核实",
    signal: "系统检测到多次“需要帮助”的入口使用",
    source: "system-pattern",
    status: "resolved",
    priority: "normal",
    studentAlias: "六年级学生 C",
    className: "六年级（3）班",
    limitedContext: "仅提供入口使用次数和时间，不展示普通学习对话。",
    guidance: ["确认学生是否需要学习或生活支持", "由人工记录核实结果"],
    assignee: "陈老师 · 年级负责人",
    notes: [
      {
        id: "safety-note-03-01",
        author: "陈老师",
        body: "人工核实为学习压力求助，已安排教师陪伴并结案。",
        createdAt: "2026-07-23T14:00:00+08:00",
      },
    ],
    createdAt: "2026-07-22T11:00:00+08:00",
    updatedAt: "2026-07-23T14:00:00+08:00",
  },
]

export const auditEventFixtures: AuditEvent[] = [
  {
    id: "audit-event-01",
    actor: "王老师 · 德育负责人",
    action: "查看风险提示",
    objectType: "safety-case",
    objectId: "safety-case-02",
    purpose: "人工核实学生支持需求",
    occurredAt: "2026-07-24T14:55:00+08:00",
  },
  {
    id: "audit-event-02",
    actor: "陈老师 · 年级负责人",
    action: "记录核实结果并结案",
    objectType: "safety-case",
    objectId: "safety-case-03",
    purpose: "完成保护性反馈流程",
    occurredAt: "2026-07-23T14:00:00+08:00",
  },
  {
    id: "audit-event-03",
    actor: "系统管理员",
    action: "查看数据留存设置",
    objectType: "settings",
    objectId: "retention-settings",
    purpose: "例行配置检查",
    occurredAt: "2026-07-21T09:00:00+08:00",
  },
]
